### ISSUE TITLE
Wrong shungite amount for Vault

### ISSUE THREAD

**Issue by NeoTheOne** [switchdv/nopixel-loot-splitter#2]
![image](https://user-images.githubusercontent.com/469830/121492447-2e7c9400-c9d7-11eb-84b0-76248799056d.png)
500 shungite worth of laptops needed before any payout.

**Comment by switchdv** [comment]
The number of shungites shown here is the minimum amount required for the red laptop. Currently the vault needs 2 red hacks. Theoretically, you can still hack with only 1 red laptop as it gives you up to 3 attempts. And as such it shows only 250 shungites.

**Comment by NeoTheOne** [comment]
After you open a door with a laptop it gets used up does it not?
Is it different for red laptops?

**Comment by switchdv** [comment]
I just checked and you're right, it does get used up. I'll change it in the next update.

**Comment by NeoTheOne** [comment]
Great!

**Comment by switchdv** [comment]
This has been fixed on the recent update. Thanks for pointing it out!
