### ISSUE TITLE
Update number of heist members

### ISSUE THREAD

**Issue by theoneraul** [switchdv/nopixel-loot-splitter#3]
With updates to heist members for the Casino being 7 for some crews, should update the calculator to include higher numbers. Maybe a dropdown selection up to 8? Unless the radio buttons is easier. I haven't coded in a long time. 
Also, I was going to try and make a spreadsheet for this type of info, but figured I should Google first to see if anyone has made anything, and here we are. So thank you!

**Comment by switchdv** [comment]
@theoneraul I haven't touched this in a while, but I'm coming back to update it again. I haven't really followed the updates so far from NoPixel, so if anyone could list all the updates/changes after the Jewelry Store heist back then, it would really, really help. I'll look into this before doing any updates. Also thanks for reaching out!

**Comment by theoneraul** [comment]
Yeah, I saw the last commit was 8 months ago. I'll see what else I can clarify/add to the tickets I opened.

**Comment by switchdv** [comment]
This has been added in the last update. Also in the update: more options for bank class, supports up to 8-person split, adds gold bars as loot option, adds an explanation of the split, and more.
