### ISSUE TITLE
Update bank classes

### ISSUE THREAD

**Issue by theoneraul** [switchdv/nopixel-loot-splitter#4]
There are several new banks that have opened, Bay City, Lower Vault, Yacht, and Casino.
Bay City: 2 Thermites
Fleeca/Paleto: Now have a thermite each as well
Upper Vault: no change
Lower Vault: 1 C4 ($25k), 1 grappling gun (unsure price or can get from Bobcat Security heist), 1 Red Laptop (250 shungite), 1 Yellow Laptop (? Shungite), Black USB (unsure cost), C4 ($25k)
Yacht: Pixel pad (unsure cost)
Casino (in-progress heist): 2 C4 ($25k each), 3 Thermite (current $6k each), 4 magnets (current $6k each)

**Comment by switchdv** [comment]
@theoneraul Thank you for the details. I've seen the Bay City heist, are you sure it only requires 1 thermite not 2?

**Comment by theoneraul** [comment]
Oh, you may be right

**Comment by switchdv** [comment]
Refers to #3 after update.

**Comment by theoneraul** [comment]
That's awesome work! I'll try to pass along this tool to the NoPixel streamers/RPers.
